controllerManager:
  manager:
    image:
      repository: ghcr.io/mondoohq/mondoo-operator
      tag: v0.2.9
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 20Mi
  replicas: 1
managerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: 60679458.mondoo.com
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
metricsService:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  type: ClusterIP
